var questions = [
   ['How do you ask "Esa es tu pluma?"', 'Is that your pen?'],
   ['How do you say "Esa es mi cartera!"', "That's my purse!"],
   ['How do you ask "Que hora es?"', "What time is it?"],
   ['How do you say "Son las tres."', "It is three o'clock."],
   ['How do you ask "A que hora es la fiesta?"', "What time is the party?"],
   ['How do you say "La reunión es a las ocho."', "The meeting is at eight o'clock."],
   ['How do you ask "Te gusta mi cabello?"', "Do you like my hair?"],
   ['How do you say "Me gusta su vestido."', "I like your dress."], 
   ['How do you ask "A el le gusta los zapatos?"', 'Does he like his shoes?'],
   ['How do you say "Esas son sus camisas."', "Those are your shirts."],
   ['How do you ask "Hace calor afuera?"', "Is it hot outside?"],
   ['How do you say "Hace frio en la tienda."', "It is cold in the store."],
   ['How do you ask "Tienes tu billetera?"', "Do you have your wallet?"],
   ['How do you say "No tengo paragua."', "I do not (don't)  have the umbrella."],
   ['How do you ask "Te gusta mi falda?"', "Do you like my skirt?"],
   ['How do you say "Me gusta tu vestido."', "I like your dress."],   
   ['How do you ask "Come carne su hija?"', 'Does your daughter eat meat?'],
   ['How do you say "Esta es la camiseta favorita de mi papá!"', "This is my dad's favorite shirt."],
   ['How do you ask "A que hora es la cena?"', "At what time is dinner?"],
   ['How do you say "Mi cita con el dueño es a las once."', "My appointment with the owner is at 11 o'clock."],
   ['How do you ask "Es nublado hoy?"', "Is it cloudy today?"],
   ['How do you say "Va a llover."', "It is (it's) going to rain."],
   ['How do you ask "Te gusta mis arretes?"', "Do you like my earrings?"],
   ['How do you say "Donde está mi collar de oro."', "Where is my gold necklace?"],   
   ['How do you ask "A ella le gusta sus patalones nuevos?"', 'Does she like your new pants?'],
   ['How do you say "Aquellos están lejos."', "Those are far."],
   ['How do you say "Estes están cerca."', "These are close"],
   ['How do you say "Este está cerca."', "This is close."],
   ['How do you say "Eso no está lejos ni está cerca"', "That is not far nor is not near"],
   ['How do you say "No tengo mi tarjeta."', "I do not (don't) have my card."],
   ['How do you ask "Esos son un poco lejos?"', "Those are a little far."],
   ['How do you say "Hace sol."', "It is sunny."],   
   ['How do you ask "A ti te gusta la prepuesta?"', 'Do you like the proposal?'],
   ['What does "that suit" mean?', "Eso traje"],
   ['What does "Those jackets" mean?', "Esos sacos"],
   ['What does "These shorts" mean?', "Estes cortos"],
   ['What does "This skirt" mean?', "Esta falda"],
   ['What does "Those blouses" mean?', "Esas blusas"],
   ['What does "These dirty undies" mean?', "Estes calzoncillos sucios"],
   ['How do you say "El edificio está cerca de aqui."', "The building is close to here."],
   ['How do you say "No tengo mi tarjeta."', "I do not (don't) have my card."],
   ['How do you ask "Queda lejos?"', "Is it far?"],
   ['How do you say "Está lloviendo."', "It's raining."],  
   ['How do you ask "Tienes vos un vestido azul?"', "Do you have a blue dress?"],
   ['How do you say "Quiero una silla roja."', "I want a red chair."],
   ['How do you ask "Donde está (eso)?"', "Where is it (that)?"],
   ['How do you ask "Quieres más clientes?"', "Do you want more customers?"],
   ['How do you say "Me gustaría un vaso de jugo de piña."', "I would like a glass of pineapple juice"],
   ['How do you ask "Ella quiere venir con nosotros?"', "Does she want to come with us?"],
   ['How do you ask "Amas a David?"', "Do you love David?"],
   ['How do you say "Quiero un biftec."', "I want a steak"],
   ['How do you say "Aquellos son zapatos amarillos."', "Those are yellow shoes."],
   ['How do you say "Estes son sombreros panameños."', "These are Panamainian hats."],
   ['How do you say "Este es cuero argentino."', "This is Argentinian leather."],
   ['How do you say "Eso no es una marca buena"', "That is not (isn't) a good brand."],
   ['How do you say "Ella no tiene las entradas."', "She does not (doesn't) have the tickets."],
   ['How do you say "Esos son restuarantes españoles."', "Those are Spanish restaurants."],
   ['How do you ask "Quiere ella una copa de vino también?"', "Does she want a glass of wine as well?"],
   ['How do you say "Aquellos son vasos grandes."', "Those are big glasses."],
   ['How do you say "Estes son botellas pequenas."', "These are small bottles."],
   ['How do you say "Este es vino español."', "This is spanish wine."],
   ['How do you say "Este no es mi favorito"', "This is not my favorite."],
   ['How do you say "Nosotros no necesitamos más comida, Gracias."', "We do not (don't) need more food, thank you."],
   ['How do you ask "Eres de los estados unidos?"', "Are you from the United States?"],
   ['How do you ask "Te gusta el vino?"', "Do you like the wine?"],
   ['How do you ask "Donde queda (eso)?"', "Where is it (that)?"],
   ['How do you say "Soy argentina."', "I am Argentinian."],
   ['How do you say "Mi novio es estadounidense."', "My boyfriend is American."],
   ['How do you say "Amo mi novio."', "I love my boyfriend"],
   ['How do you say "Extraño a mis hermanas."', "I miss my sisters."],
   ['How do you ask "Extrañas tu pais?"', "Do you miss your country?"],
   ['How do you ask "Ella extraña a su mama?"', "Does she miss her mom?"],
   ['How do you ask "Como te sientes?"', "OJO: 2 WAYS (2 maneras)................ How do you feel? - or - How are you feeling?"],
   ['How do you say "Me siento bien."', "OJO: 2 WAYS (2 maneras)..................... I feel good. - or - I am (I'm) feeling good."],
   ['How do you say "Quiero un biftec."', "I want a steak."],
   ['How do you say "Cuentáme todo."', "Tell me everything."],
   ['How do you say "Dímelo."', "Tell me it."],
   ['How do you say "Dámelo."', "Give me it."],
   ['How do you say "Dale"', "O.K. - or - Come on"],
   ['How do you say "Que tonto!"', "How silly!"],
   ['How do you say "Relajate."', "Relax."],
   ['How do you say "Cuentáme todo."', "Tell me everything."],
   ['How do you say "manzana roja."', "red apple."],
   ['How do you say "manteca de mani."', "peanut butter."],
   ['How do you ask "Quieres cafe?"', "Do you want coffee?"],
   ['How do you say "Que lio!"', "What a mess!"],
   ['How do you ask "Quieres hablar?"', "Do you want to talk?"],
   ['How do you ask "Puedo preguntarte algo?"', "Can I ask you something?"],
   ['How do you ask "Que dijo el dueño?."', "What did the owner say?"],
   ['How do you ask "Con quien necesito hablar?"', "Who do I need to talk to?"],
   ['How do you ask "Es usted en carga de las compras?"', "Are you in charge of purchases?"],
   ['How do you say "Me imagino!"', "I can imagine!"],
   ['How do you say "Dáme un segundo."', "Give me a second."],
   ['How do you say "Esperáme."', "Wait for me."],
   ['How do you say "Esperáte."', "Hold on."],
   ['How do you ask "Tienes hambre?"', "Are you hungry?"],
   ['How do you ask "Estás contento?"', "Are you happy?"],
   ['How do you say "Vendo viño para una compania española."', "I sell wine for a spanish company."],
   ['How do you ask "Podemos hablar?"', "Can we talk?"],
   ['How do you say "Estoy contenta."', "I am happy."],
   ['How do you say "Hay una picina."', "There is a pool."],
   ['How do you say "Hay muchos niños."', "There are many (a lot of) kids."],
   ['How do you say "Hay que aprender mucho."', "I must learn a lot."],
   ['How do you say "Hay tres opciones."', "There are three choices."],
   ['How do you ask "Hay un baño?"', "Is there a bathroom?"],
   ['How do you ask "Hay más empleados?"', "Are there more employees?"],
   ['How do you say "Hay una piscina."', "There is a pool."],
   ['How do you say "Hay muchos hoteles."', "There are many (a lot of) hotels."],
   ['How do you say "Hay que eschucar."', "I must listen."],
   ['How do you say "Hay cinco pájaros."', "There are five birds."],
   ['How do you ask "Hay una silla?"', "Is there a chair?"],
   ['How do you ask "Hay más copas?"', "Are there more glasses?"],
   ['How do you say "No, él no es."', "No, he is not (isn't)."],
   ['How do you ask "Se baña el elefante?"', "Is the elephant taking a bath?"],
   ['How do you say "Soy una golosa (o dulcera)."', "I have a sweet tooth."],
   ['How do you say "Estoy comiendo."', "I am eating."],
   ['How do you say "Estás hablando fuerte."', "You are talking loudly."],
   ['How do you say "Estamos llegando."', "We are arriving."],
   ['How do you ask "Estás dormiendo?"', "Are you sleeping?"],
   ['How do you say "Vamos a hablar."', "We are going to talk."],
   ['How do you say "Estoy mirando una pelicula"', "I am watching a movie"],
   ['How do you say "Ella está tomando vino."', "She is drinking wine."],
   ['How do you say "Él está leyendo."', "He is reading."],
   ['How do you say "Él está tomado jugo natural."', "He is drinkng pure juice."],
   ['How do you say "Estoy haciendo mi maquillaje."', "I am doing my make-up."],
   ['How do you ask "Que vas a hacer?"', "What are you going to do?"],
   ['How do you ask "Donde vamos a ir hoy?"', "Where are we going to go today?"],
   ['How do you say "Voy a hacer el siguente..."', "I am going to do the following..."],
   ['How do you ask "Cuanto va a comprar?"', "How many are you going to buy?"],
   ['How do you say "Vamos a ir a la piscina."', "We are going to go to the pool."],
   ['How do you say "Él va a comprar viente botellas."', "He is going to buy twenty bottles."],
   ['What does "Where?" mean.', "Donde?"],
   ['What does "What building?" mean.', "Que edificio?"],
   ['What does "How is it?" mean.', "Como es?"],
   ['What does "How many bottles?" mean.', "Cuantas botellas?"],
   ['What does "How much does it cost?" mean.', "Cuanto cuesta?"],
   ['What does "Who?" mean.', "Quien?"],
   ['What does "Where?" mean.', "Donde?"],
   ['What does "Who are you?" mean.', "Quien sos?"],
   ['What does "Where is it?" mean.', "Donde está?"],
   ['What does "How many do you want?" mean.', "Cuantas quieres?"],
   ['What does "How much does it weigh?" mean.', "Cuanto pesa?"],
   ['What does "Who is he?" mean.', "Quien es él?"],
   ['How do you say "Donde?"', "Where?"],
   ['How do you ask "Que lugar?"', "What place?"],
   ['How do you ask "Como está señor?"', "How are you sir?"],
   ['How do you ask "Cuantas bottles le gustaría?"', "How many bottle would you like?"],
   ['How do you say "Cuanto cuesta?"', "How much does it cost?"],
   ['How do you ask "Que tan lejos está?"', "How far is it?"],
   ['How do you ask "Cuanto tiempo es?"', "How much time is it?"],
   ['How do you ask "Quien es el dueño?..."', "How is the owner?"],
   ['How do you ask "Puedo hablar con el chef?"', "Can I talk to the chef?"],
   ['How do you ask "Tienes cinco minutos?"', "Do you have five minutes?"],
   ['How do you ask "Donde está?"', "Where is it?"],
   ['How do you say "Sirve queso español aqui?"', "Do you serve spanish cheese here?"],
   ['How do you ask "Quantas quiere señora?"', "How many do you want ma'am (miss)?"],
   ['How do you ask "Cuantos hay?"', "How many are there?"],
   ['How do you ask "Cuantas bottles le gustaría?"', "How many bottle would you like?"],
   ['How do you say "Cuanto tiempo tiene para hablar?"', "How much time do you have to talk?"],
   ['How do you ask "Puedo ofercerle un gustacíon el martes?"', "Can I offer you a wine tasting on Tuesday?"]
];